import 'package:flutter/material.dart';

class GameLevel {
  final List<String> letters;
  final List<Map<String, dynamic>> grid;
  final int rows;
  final int cols;
  final List<Offset>? preFilled;

  GameLevel({
    required this.letters,
    required this.grid,
    required this.rows,
    required this.cols,
    this.preFilled,
  });
}

final List<GameLevel> allLevels = [
  // LEVEL 1
  GameLevel(
    letters: ["E", "I", "S", "T"],
    rows: 8,
    cols: 10,
    grid: [
      {"word": "SITE", "x": 3, "y": 4, "dir": "h"},
      {"word": "TIES", "x": 3, "y": 1, "dir": "v"},
      {"word": "ITS", "x": 4, "y": 4, "dir": "v"},
      {"word": "SET", "x": 5, "y": 2, "dir": "v"},
      {"word": "EST", "x": 6, "y": 4, "dir": "v"},
      {"word": "SIT", "x": 1, "y": 1, "dir": "h"},
      {"word": "TIE", "x": 1, "y": 3, "dir": "h"},
      {"word": "STE", "x": 5, "y": 2, "dir": "h"},
      {"word": "SIE", "x": 6, "y": 5, "dir": "h"},
    ],
  ),
  // LEVEL 2
  GameLevel(
    letters: ["D", "N", "O", "W"],
    rows: 8,
    cols: 7,
    grid: [
      {"word": "DOWN", "x": 1, "y": 5, "dir": "h"},
      {"word": "NOW", "x": 2, "y": 4, "dir": "v"},
      {"word": "OWN", "x": 4, "y": 3, "dir": "v"},
      {"word": "WON", "x": 3, "y": 3, "dir": "h"},
      {"word": "DON", "x": 5, "y": 1, "dir": "v"},
      {"word": "DOW", "x": 3, "y": 1, "dir": "v"},
    ],
  ),
  // LEVEL 3
  GameLevel(
    letters: ["A", "H", "N", "S"],
    rows: 9,
    cols: 7,
    grid: [
      {"word": "HANS", "x": 2, "y": 3, "dir": "h"},
      {"word": "HAS", "x": 2, "y": 3, "dir": "v"},
      {"word": "SAN", "x": 4, "y": 1, "dir": "v"},
      {"word": "ASH", "x": 1, "y": 5, "dir": "h"},
      {"word": "NHS", "x": 2, "y": 1, "dir": "h"},
      {"word": "ASN", "x": 1, "y": 5, "dir": "v"},
    ],
  ),
  // LEVEL 4
  GameLevel(
    letters: ["A", "C", "H", "S"],
    rows: 6,
    cols: 7,
    grid: [
      {"word": "CASH", "x": 1, "y": 3, "dir": "h"},
      {"word": "HAS", "x": 2, "y": 2, "dir": "v"},
      {"word": "ASH", "x": 4, "y": 1, "dir": "v"},
      {"word": "CAS", "x": 3, "y": 1, "dir": "h"},
    ],
  ),
  // LEVEL 5
  GameLevel(
    letters: ["A", "I", "M", "U"],
    rows: 5,
    cols: 8,
    grid: [
      {"word": "MAUI", "x": 3, "y": 3, "dir": "h"},
      {"word": "AIM", "x": 3, "y": 1, "dir": "v"},
      {"word": "MAI", "x": 6, "y": 1, "dir": "v"},
      {"word": "MIA", "x": 1, "y": 1, "dir": "h"},
    ],
  ),
  // LEVEL 6
  GameLevel(
    letters: ["G", "I", "N", "P"],
    rows: 6,
    cols: 6,
    grid: [
      {"word": "PING", "x": 1, "y": 2, "dir": "h"},
      {"word": "PIN", "x": 1, "y": 2, "dir": "v"},
      {"word": "ING", "x": 3, "y": 1, "dir": "v"},
    ],
  ),
  // LEVEL 7
  GameLevel(
    letters: ["A", "E", "H", "Y"],
    rows: 7,
    cols: 6,
    grid: [
      {"word": "YEAH", "x": 1, "y": 3, "dir": "h"},
      {"word": "HEY", "x": 1, "y": 1, "dir": "v"},
      {"word": "AYE", "x": 3, "y": 3, "dir": "v"},
      {"word": "YEA", "x": 2, "y": 5, "dir": "h"},
      {"word": "HAY", "x": 1, "y": 1, "dir": "h"},
    ],
  ),
  // LEVEL 8
  GameLevel(
    letters: ["N", "O", "S", "W"],
    rows: 9,
    cols: 9,
    grid: [
      {"word": "OWNS", "x": 3, "y": 3, "dir": "h"},
      {"word": "SNOW", "x": 3, "y": 1, "dir": "v"},
      {"word": "NOW", "x": 5, "y": 3, "dir": "v"},
      {"word": "OWN", "x": 1, "y": 2, "dir": "h"},
      {"word": "SON", "x": 3, "y": 1, "dir": "h"},
      {"word": "WON", "x": 5, "y": 5, "dir": "h"},
      {"word": "NSW", "x": 1, "y": 4, "dir": "h"},
      {"word": "ONS", "x": 6, "y": 5, "dir": "v"},
    ],
  ),
  // LEVEL 9
  GameLevel(
    letters: ["A", "B", "L", "S"],
    rows: 7,
    cols: 8,
    grid: [
      {"word": "LABS", "x": 3, "y": 3, "dir": "h"},
      {"word": "LAS", "x": 3, "y": 3, "dir": "v"},
      {"word": "LAB", "x": 5, "y": 1, "dir": "v"},
      {"word": "LBS", "x": 1, "y": 5, "dir": "h"},
    ],
  ),
  // LEVEL 10
  GameLevel(
    letters: ["H", "O", "S", "T"],
    rows: 7,
    cols: 6,
    grid: [
      {"word": "HOST", "x": 1, "y": 3, "dir": "h"},
      {"word": "SHOT", "x": 1, "y": 2, "dir": "v"},
      {"word": "HOT", "x": 4, "y": 1, "dir": "v"},
    ],
  ),
  // LEVEL 11
  GameLevel(
    letters: ["D", "E", "I", "S"],
    rows: 9,
    cols: 9,
    grid: [
      {"word": "DIES", "x": 3, "y": 4, "dir": "h"},
      {"word": "SIDE", "x": 3, "y": 2, "dir": "v"},
      {"word": "DIE", "x": 5, "y": 2, "dir": "v"},
      {"word": "DES", "x": 1, "y": 2, "dir": "h"},
      {"word": "IDE", "x": 1, "y": 5, "dir": "h"},
      {"word": "DIS", "x": 5, "y": 2, "dir": "h"},
      {"word": "SIE", "x": 6, "y": 4, "dir": "v"},
      {"word": "EDS", "x": 1, "y": 1, "dir": "v"},
      {"word": "IDS", "x": 1, "y": 5, "dir": "v"},
    ],
  ),
  // LEVEL 12
  GameLevel(
    letters: ["E", "M", "N", "U"],
    rows: 7,
    cols: 6,
    grid: [
      {"word": "MENU", "x": 1, "y": 3, "dir": "h"},
      {"word": "MEN", "x": 1, "y": 3, "dir": "v"},
      {"word": "UNE", "x": 2, "y": 1, "dir": "v"},
    ],
  ),
  // LEVEL 13
  GameLevel(
    letters: ["E", "E", "L", "S", "T"],
    rows: 11,
    cols: 9,
    grid: [
      {"word": "STEEL", "x": 3, "y": 5, "dir": "h"},
      {"word": "ELSE", "x": 3, "y": 3, "dir": "v"},
      {"word": "LETS", "x": 5, "y": 4, "dir": "v"},
      {"word": "SEE", "x": 2, "y": 3, "dir": "h"},
      {"word": "SET", "x": 5, "y": 7, "dir": "h"},
      {"word": "LET", "x": 7, "y": 5, "dir": "v"},
      {"word": "EST", "x": 6, "y": 7, "dir": "v"},
      {"word": "LEE", "x": 1, "y": 6, "dir": "h"},
      {"word": "LES", "x": 2, "y": 1, "dir": "v"},
      {"word": "TEE", "x": 4, "y": 1, "dir": "v"},
      {"word": "STE", "x": 5, "y": 9, "dir": "h"},
    ],
  ),
  // LEVEL 14
  GameLevel(
    letters: ["L", "M", "Q", "S", "Y"],
    rows: 5,
    cols: 7,
    grid: [
      {"word": "MYSQL", "x": 1, "y": 1, "dir": "h"},
      {"word": "SQL", "x": 3, "y": 1, "dir": "v"},
      {"word": "MLS", "x": 1, "y": 1, "dir": "v"},
    ],
  ),
  // LEVEL 15
  GameLevel(
    letters: ["A", "B", "H", "S", "T"],
    rows: 11,
    cols: 11,
    grid: [
      {"word": "BATHS", "x": 3, "y": 4, "dir": "h"},
      {"word": "BATH", "x": 3, "y": 4, "dir": "v"},
      {"word": "TABS", "x": 5, "y": 4, "dir": "v"},
      {"word": "HATS", "x": 7, "y": 1, "dir": "v"},
      {"word": "HAS", "x": 3, "y": 7, "dir": "h"},
      {"word": "SAT", "x": 1, "y": 6, "dir": "h"},
      {"word": "HAT", "x": 7, "y": 1, "dir": "h"},
      {"word": "TAB", "x": 7, "y": 3, "dir": "h"},
      {"word": "ASH", "x": 4, "y": 7, "dir": "v"},
      {"word": "ABS", "x": 1, "y": 4, "dir": "v"},
      {"word": "BAT", "x": 5, "y": 6, "dir": "h"},
      {"word": "TBA", "x": 4, "y": 2, "dir": "v"},
    ],
  ),
  // LEVEL 16
  GameLevel(
    letters: ["A", "I", "J", "L", "U"],
    rows: 8,
    cols: 7,
    grid: [
      {"word": "JULIA", "x": 1, "y": 3, "dir": "h"},
      {"word": "JAIL", "x": 1, "y": 3, "dir": "v"},
      {"word": "JUL", "x": 3, "y": 1, "dir": "v"},
      {"word": "ALI", "x": 5, "y": 3, "dir": "v"},
    ],
  ),
  // LEVEL 17
  GameLevel(
    letters: ["A", "E", "K", "N", "R"],
    rows: 8,
    cols: 11,
    grid: [
      {"word": "KAREN", "x": 3, "y": 5, "dir": "h"},
      {"word": "NEAR", "x": 4, "y": 3, "dir": "v"},
      {"word": "RANK", "x": 7, "y": 3, "dir": "v"},
      {"word": "EARN", "x": 1, "y": 3, "dir": "h"},
      {"word": "ARE", "x": 6, "y": 3, "dir": "h"},
      {"word": "ERA", "x": 1, "y": 3, "dir": "v"},
      {"word": "KEN", "x": 7, "y": 6, "dir": "h"},
      {"word": "RAN", "x": 9, "y": 4, "dir": "v"},
      {"word": "EAR", "x": 3, "y": 1, "dir": "v"},
      {"word": "RNA", "x": 6, "y": 1, "dir": "v"},
    ],
  ),
  // LEVEL 18
  GameLevel(
    letters: ["A", "D", "E", "L", "Y"],
    rows: 8,
    cols: 12,
    grid: [
      {"word": "DELAY", "x": 4, "y": 4, "dir": "h"},
      {"word": "LEAD", "x": 4, "y": 1, "dir": "v"},
      {"word": "DEAL", "x": 6, "y": 1, "dir": "v"},
      {"word": "LADY", "x": 8, "y": 1, "dir": "v"},
      {"word": "DALE", "x": 1, "y": 2, "dir": "h"},
      {"word": "YALE", "x": 2, "y": 1, "dir": "v"},
      {"word": "DAY", "x": 8, "y": 3, "dir": "h"},
      {"word": "LED", "x": 4, "y": 1, "dir": "h"},
      {"word": "LAY", "x": 8, "y": 1, "dir": "h"},
      {"word": "AYE", "x": 7, "y": 4, "dir": "v"},
      {"word": "YEA", "x": 10, "y": 3, "dir": "v"},
    ],
  ),
  // LEVEL 19
  GameLevel(
    letters: ["A", "C", "E", "S", "S"],
    rows: 8,
    cols: 11,
    grid: [
      {"word": "CASES", "x": 3, "y": 3, "dir": "h"},
      {"word": "CASE", "x": 3, "y": 3, "dir": "v"},
      {"word": "SEAS", "x": 5, "y": 3, "dir": "v"},
      {"word": "SEA", "x": 4, "y": 1, "dir": "v"},
      {"word": "SEC", "x": 7, "y": 3, "dir": "v"},
      {"word": "CSS", "x": 1, "y": 5, "dir": "h"},
      {"word": "ACE", "x": 6, "y": 1, "dir": "v"},
      {"word": "SAS", "x": 2, "y": 1, "dir": "h"},
      {"word": "CAS", "x": 7, "y": 5, "dir": "h"},
    ],
  ),
  // LEVEL 20
  GameLevel(
    letters: ["E", "I", "S", "V", "W"],
    rows: 9,
    cols: 7,
    grid: [
      {"word": "WIVES", "x": 1, "y": 4, "dir": "h"},
      {"word": "VIEWS", "x": 1, "y": 1, "dir": "v"},
      {"word": "VIEW", "x": 3, "y": 4, "dir": "v"},
      {"word": "WISE", "x": 4, "y": 1, "dir": "v"},
      {"word": "SIE", "x": 5, "y": 4, "dir": "v"},
    ],
  ),
  // LEVEL 21
  GameLevel(
    letters: ["C", "N", "O", "R", "W"],
    rows: 8,
    cols: 13,
    grid: [
      {"word": "CROWN", "x": 5, "y": 2, "dir": "h"},
      {"word": "CORN", "x": 5, "y": 2, "dir": "v"},
      {"word": "WORN", "x": 7, "y": 1, "dir": "v"},
      {"word": "NOW", "x": 9, "y": 2, "dir": "v"},
      {"word": "OWN", "x": 3, "y": 5, "dir": "h"},
      {"word": "NOR", "x": 3, "y": 4, "dir": "v"},
      {"word": "CON", "x": 1, "y": 4, "dir": "h"},
      {"word": "WON", "x": 9, "y": 4, "dir": "h"},
      {"word": "RON", "x": 5, "y": 4, "dir": "h"},
      {"word": "COW", "x": 1, "y": 4, "dir": "v"},
    ],
  ),
  // LEVEL 22
  GameLevel(
    letters: ["H", "I", "L", "L", "S"],
    rows: 8,
    cols: 9,
    grid: [
      {"word": "HILLS", "x": 3, "y": 3, "dir": "h"},
      {"word": "HILL", "x": 3, "y": 3, "dir": "v"},
      {"word": "HIS", "x": 7, "y": 1, "dir": "v"},
      {"word": "ILL", "x": 5, "y": 2, "dir": "v"},
      {"word": "LIL", "x": 1, "y": 5, "dir": "h"},
    ],
  ),
  // LEVEL 23
  GameLevel(
    letters: ["E", "L", "S", "T", "Y"],
    rows: 9,
    cols: 11,
    grid: [
      {"word": "STYLE", "x": 3, "y": 4, "dir": "h"},
      {"word": "LETS", "x": 3, "y": 1, "dir": "v"},
      {"word": "SET", "x": 7, "y": 3, "dir": "v"},
      {"word": "YES", "x": 5, "y": 4, "dir": "v"},
      {"word": "LET", "x": 3, "y": 1, "dir": "h"},
      {"word": "YET", "x": 1, "y": 3, "dir": "h"},
      {"word": "TEL", "x": 7, "y": 5, "dir": "h"},
      {"word": "EST", "x": 4, "y": 6, "dir": "h"},
      {"word": "LES", "x": 9, "y": 5, "dir": "v"},
      {"word": "STE", "x": 7, "y": 3, "dir": "h"},
    ],
  ),
  // LEVEL 24
  GameLevel(
    letters: ["A", "B", "R", "S", "S"],
    rows: 9,
    cols: 11,
    grid: [
      {"word": "BRASS", "x": 3, "y": 4, "dir": "h"},
      {"word": "BARS", "x": 3, "y": 4, "dir": "v"},
      {"word": "BASS", "x": 5, "y": 3, "dir": "v"},
      {"word": "BRAS", "x": 7, "y": 1, "dir": "v"},
      {"word": "RSS", "x": 3, "y": 6, "dir": "h"},
      {"word": "BAR", "x": 7, "y": 1, "dir": "h"},
      {"word": "BRA", "x": 1, "y": 5, "dir": "h"},
      {"word": "ABS", "x": 1, "y": 7, "dir": "h"},
    ],
  ),
  // LEVEL 25
  GameLevel(
    letters: ["B", "B", "I", "N", "O", "R"],
    rows: 13,
    cols: 10,
    grid: [
      {"word": "RIBBON", "x": 3, "y": 5, "dir": "h"},
      {"word": "ROBIN", "x": 3, "y": 5, "dir": "v"},
      {"word": "BORN", "x": 5, "y": 5, "dir": "v"},
      {"word": "IRON", "x": 7, "y": 3, "dir": "v"},
      {"word": "BIN", "x": 1, "y": 9, "dir": "h"},
      {"word": "BOB", "x": 1, "y": 7, "dir": "h"},
      {"word": "NOR", "x": 5, "y": 8, "dir": "h"},
      {"word": "BIO", "x": 6, "y": 3, "dir": "h"},
      {"word": "ROB", "x": 1, "y": 5, "dir": "v"},
      {"word": "RON", "x": 7, "y": 8, "dir": "v"},
      {"word": "RIO", "x": 8, "y": 1, "dir": "v"},
      {"word": "ION", "x": 2, "y": 9, "dir": "v"},
      {"word": "BON", "x": 5, "y": 10, "dir": "h"},
    ],
  ),
  // LEVEL 26
  GameLevel(
    letters: ["C", "E", "I", "P", "R", "S"],
    rows: 21,
    cols: 21,
    grid: [
      {"word": "PRICES", "x": 8, "y": 9, "dir": "h"},
      {"word": "PRICE", "x": 8, "y": 9, "dir": "v"},
      {"word": "SPICE", "x": 10, "y": 7, "dir": "v"},
      {"word": "PICS", "x": 13, "y": 6, "dir": "v"},
      {"word": "RISE", "x": 7, "y": 11, "dir": "h"},
      {"word": "ERIC", "x": 12, "y": 9, "dir": "v"},
      {"word": "RICE", "x": 5, "y": 13, "dir": "h"},
      {"word": "SPEC", "x": 12, "y": 6, "dir": "h"},
      {"word": "RIPE", "x": 5, "y": 13, "dir": "v"},
      {"word": "EPIC", "x": 15, "y": 3, "dir": "v"},
      {"word": "PER", "x": 5, "y": 15, "dir": "h"},
      {"word": "SEP", "x": 14, "y": 3, "dir": "h"},
      {"word": "PRE", "x": 3, "y": 16, "dir": "h"},
      {"word": "ICE", "x": 12, "y": 11, "dir": "h"},
      {"word": "SEC", "x": 14, "y": 10, "dir": "v"},
      {"word": "PIC", "x": 3, "y": 16, "dir": "v"},
      {"word": "SRC", "x": 14, "y": 10, "dir": "h"},
      {"word": "SIR", "x": 15, "y": 8, "dir": "v"},
      {"word": "RES", "x": 8, "y": 7, "dir": "h"},
      {"word": "PCS", "x": 12, "y": 4, "dir": "v"},
      {"word": "SCI", "x": 3, "y": 14, "dir": "h"},
      {"word": "PCI", "x": 1, "y": 17, "dir": "h"},
      {"word": "REP", "x": 7, "y": 15, "dir": "v"},
      {"word": "SRI", "x": 15, "y": 8, "dir": "h"},
      {"word": "ISP", "x": 15, "y": 5, "dir": "h"},
      {"word": "PIE", "x": 9, "y": 5, "dir": "v"},
      {"word": "RIP", "x": 16, "y": 1, "dir": "v"},
      {"word": "SER", "x": 14, "y": 1, "dir": "h"},
      {"word": "SIE", "x": 17, "y": 7, "dir": "v"},
      {"word": "ERP", "x": 10, "y": 4, "dir": "h"},
      {"word": "IRS", "x": 3, "y": 12, "dir": "v"},
      {"word": "PSI", "x": 1, "y": 17, "dir": "v"},
      {"word": "SIP", "x": 7, "y": 5, "dir": "h"},
      {"word": "SIC", "x": 17, "y": 7, "dir": "h"},
      {"word": "CIR", "x": 14, "y": 12, "dir": "h"},
      {"word": "IPS", "x": 6, "y": 17, "dir": "h"},
    ],
  ),
  // LEVEL 27
  GameLevel(
    letters: ["A", "D", "E", "I", "L", "S"],
    rows: 23,
    cols: 20,
    grid: [
      {"word": "LADIES", "x": 6, "y": 11, "dir": "h"},
      {"word": "DEALS", "x": 6, "y": 8, "dir": "v"},
      {"word": "IDEAS", "x": 8, "y": 10, "dir": "v"},
      {"word": "LEADS", "x": 10, "y": 10, "dir": "v"},
      {"word": "IDEAL", "x": 5, "y": 8, "dir": "h"},
      {"word": "SLIDE", "x": 10, "y": 14, "dir": "h"},
      {"word": "ASIDE", "x": 7, "y": 4, "dir": "v"},
      {"word": "SAID", "x": 7, "y": 13, "dir": "h"},
      {"word": "SALE", "x": 9, "y": 6, "dir": "v"},
      {"word": "SIDE", "x": 12, "y": 13, "dir": "v"},
      {"word": "LEAD", "x": 14, "y": 13, "dir": "v"},
      {"word": "IDEA", "x": 3, "y": 10, "dir": "h"},
      {"word": "DEAL", "x": 5, "y": 4, "dir": "h"},
      {"word": "AIDS", "x": 3, "y": 12, "dir": "h"},
      {"word": "DIAL", "x": 14, "y": 16, "dir": "h"},
      {"word": "SEAL", "x": 9, "y": 6, "dir": "h"},
      {"word": "LIES", "x": 14, "y": 13, "dir": "h"},
      {"word": "LISA", "x": 3, "y": 9, "dir": "v"},
      {"word": "LAID", "x": 5, "y": 1, "dir": "v"},
      {"word": "ISLE", "x": 9, "y": 16, "dir": "h"},
      {"word": "DALE", "x": 5, "y": 12, "dir": "v"},
      {"word": "DIES", "x": 16, "y": 11, "dir": "v"},
      {"word": "ADSL", "x": 8, "y": 1, "dir": "v"},
      {"word": "IDLE", "x": 15, "y": 16, "dir": "v"},
      {"word": "SAIL", "x": 11, "y": 5, "dir": "v"},
      {"word": "SEA", "x": 3, "y": 2, "dir": "h"},
      {"word": "ADS", "x": 1, "y": 11, "dir": "h"},
      {"word": "LAS", "x": 17, "y": 16, "dir": "v"},
      {"word": "AID", "x": 9, "y": 15, "dir": "v"},
      {"word": "LED", "x": 11, "y": 16, "dir": "v"},
      {"word": "DIE", "x": 3, "y": 15, "dir": "h"},
      {"word": "DEL", "x": 1, "y": 9, "dir": "h"},
      {"word": "DES", "x": 16, "y": 11, "dir": "h"},
      {"word": "LES", "x": 15, "y": 18, "dir": "h"},
      {"word": "DSL", "x": 8, "y": 2, "dir": "h"},
      {"word": "LIE", "x": 13, "y": 19, "dir": "h"},
      {"word": "SAD", "x": 3, "y": 2, "dir": "v"},
      {"word": "DAS", "x": 3, "y": 15, "dir": "v"},
      {"word": "ALI", "x": 5, "y": 6, "dir": "v"},
      {"word": "IDE", "x": 10, "y": 18, "dir": "h"},
      {"word": "DIS", "x": 18, "y": 9, "dir": "v"},
      {"word": "SIE", "x": 2, "y": 7, "dir": "v"},
      {"word": "EDS", "x": 1, "y": 17, "dir": "h"},
      {"word": "LID", "x": 11, "y": 8, "dir": "h"},
      {"word": "ISA", "x": 14, "y": 19, "dir": "v"},
      {"word": "IDS", "x": 10, "y": 18, "dir": "v"},
    ],
  ),
  // LEVEL 28
  GameLevel(
    letters: ["E", "E", "M", "P", "T", "X"],
    rows: 11,
    cols: 12,
    grid: [
      {"word": "EXEMPT", "x": 3, "y": 5, "dir": "h"},
      {"word": "MEET", "x": 3, "y": 4, "dir": "v"},
      {"word": "TEMP", "x": 5, "y": 4, "dir": "v"},
      {"word": "PETE", "x": 7, "y": 5, "dir": "v"},
      {"word": "PET", "x": 8, "y": 3, "dir": "v"},
      {"word": "MET", "x": 1, "y": 7, "dir": "h"},
      {"word": "EXP", "x": 7, "y": 8, "dir": "h"},
      {"word": "PEE", "x": 8, "y": 3, "dir": "h"},
      {"word": "EXT", "x": 2, "y": 7, "dir": "v"},
      {"word": "TEE", "x": 9, "y": 1, "dir": "v"},
      {"word": "TEX", "x": 2, "y": 9, "dir": "h"},
      {"word": "TMP", "x": 9, "y": 6, "dir": "v"},
    ],
  ),
  // LEVEL 29
  GameLevel(
    letters: ["E", "L", "P", "P", "R", "U"],
    rows: 11,
    cols: 14,
    grid: [
      {"word": "PURPLE", "x": 5, "y": 5, "dir": "h"},
      {"word": "UPPER", "x": 5, "y": 4, "dir": "v"},
      {"word": "RULE", "x": 7, "y": 5, "dir": "v"},
      {"word": "PERL", "x": 9, "y": 2, "dir": "v"},
      {"word": "PURE", "x": 2, "y": 7, "dir": "h"},
      {"word": "PERU", "x": 2, "y": 4, "dir": "h"},
      {"word": "PREP", "x": 9, "y": 2, "dir": "h"},
      {"word": "PER", "x": 2, "y": 7, "dir": "v"},
      {"word": "URL", "x": 1, "y": 9, "dir": "h"},
      {"word": "EUR", "x": 10, "y": 5, "dir": "v"},
      {"word": "PRE", "x": 7, "y": 3, "dir": "h"},
      {"word": "REP", "x": 2, "y": 2, "dir": "v"},
      {"word": "ERP", "x": 7, "y": 8, "dir": "h"},
      {"word": "LEU", "x": 11, "y": 1, "dir": "v"},
    ],
  ),
  // LEVEL 30
  GameLevel(
    letters: ["A", "I", "N", "N", "S", "S"],
    rows: 12,
    cols: 13,
    grid: [
      {"word": "NISSAN", "x": 4, "y": 6, "dir": "h"},
      {"word": "ASIN", "x": 4, "y": 3, "dir": "v"},
      {"word": "INNS", "x": 5, "y": 6, "dir": "v"},
      {"word": "SANS", "x": 6, "y": 3, "dir": "v"},
      {"word": "ISSN", "x": 9, "y": 3, "dir": "v"},
      {"word": "SAN", "x": 7, "y": 6, "dir": "v"},
      {"word": "INN", "x": 3, "y": 8, "dir": "h"},
      {"word": "SIN", "x": 8, "y": 3, "dir": "h"},
      {"word": "IAN", "x": 3, "y": 8, "dir": "v"},
      {"word": "INS", "x": 2, "y": 4, "dir": "h"},
      {"word": "ASN", "x": 10, "y": 1, "dir": "v"},
      {"word": "SAS", "x": 9, "y": 5, "dir": "h"},
      {"word": "ISA", "x": 1, "y": 9, "dir": "h"},
    ],
  ),
  // LEVEL 31
  GameLevel(
    letters: ["E", "G", "H", "N", "R", "U"],
    rows: 11,
    cols: 12,
    grid: [
      {"word": "HUNGER", "x": 3, "y": 4, "dir": "h"},
      {"word": "HUGE", "x": 3, "y": 4, "dir": "v"},
      {"word": "HUNG", "x": 5, "y": 2, "dir": "v"},
      {"word": "URGE", "x": 7, "y": 1, "dir": "v"},
      {"word": "HER", "x": 2, "y": 7, "dir": "h"},
      {"word": "RUN", "x": 8, "y": 4, "dir": "v"},
      {"word": "EUR", "x": 6, "y": 1, "dir": "h"},
      {"word": "GNU", "x": 1, "y": 5, "dir": "h"},
      {"word": "GUN", "x": 6, "y": 6, "dir": "h"},
      {"word": "REG", "x": 4, "y": 7, "dir": "v"},
      {"word": "ENG", "x": 1, "y": 3, "dir": "v"},
      {"word": "GEN", "x": 6, "y": 6, "dir": "v"},
      {"word": "UNE", "x": 8, "y": 5, "dir": "h"},
      {"word": "RUG", "x": 2, "y": 9, "dir": "h"},
    ],
  ),
  // LEVEL 32
  GameLevel(
    letters: ["E", "E", "H", "L", "S", "W"],
    rows: 11,
    cols: 10,
    grid: [
      {"word": "WHEELS", "x": 3, "y": 5, "dir": "h"},
      {"word": "WHEEL", "x": 3, "y": 5, "dir": "v"},
      {"word": "WELSH", "x": 4, "y": 1, "dir": "v"},
      {"word": "ELSE", "x": 5, "y": 5, "dir": "v"},
      {"word": "HEEL", "x": 7, "y": 2, "dir": "v"},
      {"word": "SEE", "x": 8, "y": 5, "dir": "v"},
      {"word": "SHE", "x": 1, "y": 7, "dir": "h"},
      {"word": "LEE", "x": 3, "y": 2, "dir": "h"},
      {"word": "LES", "x": 6, "y": 3, "dir": "h"},
    ],
  ),
  // LEVEL 33
  GameLevel(
    letters: ["A", "I", "R", "S", "T", "V"],
    rows: 15,
    cols: 18,
    grid: [
      {"word": "TRAVIS", "x": 6, "y": 8, "dir": "h"},
      {"word": "VISTA", "x": 6, "y": 5, "dir": "v"},
      {"word": "STAR", "x": 8, "y": 6, "dir": "v"},
      {"word": "ARTS", "x": 11, "y": 5, "dir": "v"},
      {"word": "VISA", "x": 3, "y": 9, "dir": "h"},
      {"word": "VAST", "x": 10, "y": 5, "dir": "h"},
      {"word": "RATS", "x": 3, "y": 7, "dir": "h"},
      {"word": "ITS", "x": 10, "y": 8, "dir": "v"},
      {"word": "ART", "x": 13, "y": 3, "dir": "v"},
      {"word": "AIR", "x": 3, "y": 5, "dir": "v"},
      {"word": "VIA", "x": 3, "y": 9, "dir": "v"},
      {"word": "SAT", "x": 5, "y": 9, "dir": "v"},
      {"word": "VAR", "x": 12, "y": 3, "dir": "h"},
      {"word": "VAT", "x": 2, "y": 5, "dir": "h"},
      {"word": "SIR", "x": 10, "y": 10, "dir": "h"},
      {"word": "SIT", "x": 4, "y": 3, "dir": "v"},
      {"word": "SRI", "x": 1, "y": 10, "dir": "h"},
      {"word": "TVS", "x": 11, "y": 7, "dir": "h"},
      {"word": "RAT", "x": 12, "y": 10, "dir": "v"},
      {"word": "TRI", "x": 5, "y": 11, "dir": "h"},
      {"word": "IST", "x": 3, "y": 3, "dir": "h"},
      {"word": "AVI", "x": 4, "y": 7, "dir": "v"},
      {"word": "ATI", "x": 12, "y": 11, "dir": "h"},
      {"word": "STR", "x": 14, "y": 1, "dir": "v"},
      {"word": "TAR", "x": 14, "y": 2, "dir": "h"},
      {"word": "IRS", "x": 6, "y": 6, "dir": "h"},
      {"word": "ISA", "x": 1, "y": 9, "dir": "v"},
      {"word": "IRA", "x": 7, "y": 11, "dir": "v"},
    ],
  ),
  // LEVEL 34
  GameLevel(
    letters: ["E", "I", "P", "R", "S", "Z"],
    rows: 16,
    cols: 12,
    grid: [
      {"word": "PRIZES", "x": 2, "y": 6, "dir": "h"},
      {"word": "PRIZE", "x": 2, "y": 6, "dir": "v"},
      {"word": "SIZE", "x": 4, "y": 5, "dir": "v"},
      {"word": "RISE", "x": 6, "y": 3, "dir": "v"},
      {"word": "RIPE", "x": 1, "y": 8, "dir": "h"},
      {"word": "PER", "x": 1, "y": 10, "dir": "h"},
      {"word": "SEP", "x": 7, "y": 6, "dir": "v"},
      {"word": "PRE", "x": 5, "y": 3, "dir": "h"},
      {"word": "ZIP", "x": 5, "y": 1, "dir": "v"},
      {"word": "RES", "x": 3, "y": 10, "dir": "v"},
      {"word": "SRI", "x": 3, "y": 2, "dir": "h"},
      {"word": "ISP", "x": 2, "y": 12, "dir": "h"},
      {"word": "PIE", "x": 7, "y": 8, "dir": "h"},
      {"word": "SER", "x": 3, "y": 2, "dir": "v"},
      {"word": "SIE", "x": 7, "y": 1, "dir": "v"},
      {"word": "ERP", "x": 9, "y": 8, "dir": "v"},
      {"word": "IRS", "x": 2, "y": 12, "dir": "v"},
      {"word": "PSI", "x": 4, "y": 12, "dir": "v"},
      {"word": "SIP", "x": 7, "y": 1, "dir": "h"},
      {"word": "IPS", "x": 8, "y": 10, "dir": "h"},
    ],
  ),
  // LEVEL 35
  GameLevel(
    letters: ["E", "I", "N", "T", "T", "Y"],
    rows: 11,
    cols: 12,
    grid: [
      {"word": "ENTITY", "x": 2, "y": 5, "dir": "h"},
      {"word": "TINY", "x": 3, "y": 3, "dir": "v"},
      {"word": "TENT", "x": 6, "y": 5, "dir": "v"},
      {"word": "YET", "x": 1, "y": 3, "dir": "h"},
      {"word": "NET", "x": 6, "y": 7, "dir": "h"},
      {"word": "INT", "x": 4, "y": 8, "dir": "h"},
      {"word": "TEN", "x": 8, "y": 7, "dir": "v"},
      {"word": "TIE", "x": 2, "y": 1, "dir": "v"},
      {"word": "ENT", "x": 8, "y": 8, "dir": "h"},
      {"word": "TIN", "x": 4, "y": 7, "dir": "v"},
      {"word": "YEN", "x": 2, "y": 9, "dir": "h"},
    ],
  ),
  // LEVEL 36
  GameLevel(
    letters: ["B", "E", "I", "R", "S", "T"],
    rows: 20,
    cols: 15,
    grid: [
      {"word": "TRIBES", "x": 5, "y": 10, "dir": "h"},
      {"word": "TRIES", "x": 5, "y": 10, "dir": "v"},
      {"word": "TIRES", "x": 7, "y": 9, "dir": "v"},
      {"word": "TRIBE", "x": 9, "y": 6, "dir": "v"},
      {"word": "SITE", "x": 10, "y": 10, "dir": "v"},
      {"word": "BEST", "x": 3, "y": 14, "dir": "h"},
      {"word": "REST", "x": 6, "y": 6, "dir": "h"},
      {"word": "RISE", "x": 4, "y": 12, "dir": "h"},
      {"word": "BITS", "x": 8, "y": 8, "dir": "h"},
      {"word": "TIES", "x": 10, "y": 12, "dir": "h"},
      {"word": "TIRE", "x": 6, "y": 14, "dir": "v"},
      {"word": "TIER", "x": 6, "y": 3, "dir": "v"},
      {"word": "BITE", "x": 3, "y": 14, "dir": "v"},
      {"word": "ITS", "x": 8, "y": 4, "dir": "v"},
      {"word": "SET", "x": 12, "y": 11, "dir": "v"},
      {"word": "BIT", "x": 4, "y": 3, "dir": "h"},
      {"word": "EST", "x": 11, "y": 7, "dir": "v"},
      {"word": "RES", "x": 6, "y": 16, "dir": "h"},
      {"word": "SIT", "x": 1, "y": 16, "dir": "h"},
      {"word": "BET", "x": 4, "y": 3, "dir": "v"},
      {"word": "TIE", "x": 4, "y": 5, "dir": "h"},
      {"word": "SRI", "x": 5, "y": 1, "dir": "v"},
      {"word": "TRI", "x": 11, "y": 9, "dir": "h"},
      {"word": "IST", "x": 8, "y": 4, "dir": "h"},
      {"word": "STE", "x": 8, "y": 16, "dir": "v"},
      {"word": "SER", "x": 1, "y": 16, "dir": "v"},
      {"word": "STR", "x": 5, "y": 1, "dir": "h"},
      {"word": "SIE", "x": 2, "y": 4, "dir": "h"},
      {"word": "IRS", "x": 9, "y": 2, "dir": "v"},
    ],
  ),
  // LEVEL 37
  GameLevel(
    letters: ["B", "E", "F", "I", "L", "R", "Y"],
    rows: 13,
    cols: 14,
    grid: [
      {"word": "BRIEFLY", "x": 5, "y": 6, "dir": "h"},
      {"word": "BRIEF", "x": 5, "y": 6, "dir": "v"},
      {"word": "FIBER", "x": 6, "y": 2, "dir": "v"},
      {"word": "FLYER", "x": 8, "y": 3, "dir": "v"},
      {"word": "FIBRE", "x": 1, "y": 9, "dir": "h"},
      {"word": "LIFE", "x": 10, "y": 6, "dir": "v"},
      {"word": "FILE", "x": 5, "y": 10, "dir": "h"},
      {"word": "FIRE", "x": 8, "y": 3, "dir": "h"},
      {"word": "RELY", "x": 9, "y": 9, "dir": "h"},
      {"word": "FEB", "x": 4, "y": 4, "dir": "h"},
      {"word": "FRI", "x": 1, "y": 9, "dir": "v"},
      {"word": "FLY", "x": 7, "y": 9, "dir": "v"},
      {"word": "LIB", "x": 3, "y": 7, "dir": "v"},
      {"word": "REF", "x": 4, "y": 2, "dir": "h"},
      {"word": "LIE", "x": 11, "y": 1, "dir": "v"},
      {"word": "FBI", "x": 9, "y": 1, "dir": "v"},
      {"word": "BYE", "x": 12, "y": 8, "dir": "v"},
    ],
  ),
  // LEVEL 38
  GameLevel(
    letters: ["B", "D", "E", "I", "L", "R", "U"],
    rows: 14,
    cols: 18,
    grid: [
      {"word": "BUILDER", "x": 5, "y": 5, "dir": "h"},
      {"word": "BURIED", "x": 5, "y": 5, "dir": "v"},
      {"word": "BUILD", "x": 7, "y": 3, "dir": "v"},
      {"word": "BRIDE", "x": 9, "y": 2, "dir": "v"},
      {"word": "RULED", "x": 11, "y": 5, "dir": "v"},
      {"word": "BLUE", "x": 2, "y": 9, "dir": "h"},
      {"word": "RULE", "x": 9, "y": 3, "dir": "h"},
      {"word": "BIRD", "x": 8, "y": 9, "dir": "h"},
      {"word": "RIDE", "x": 5, "y": 7, "dir": "h"},
      {"word": "IDLE", "x": 3, "y": 7, "dir": "v"},
      {"word": "REID", "x": 10, "y": 9, "dir": "v"},
      {"word": "RED", "x": 12, "y": 2, "dir": "v"},
      {"word": "DUE", "x": 5, "y": 10, "dir": "h"},
      {"word": "URL", "x": 11, "y": 6, "dir": "h"},
      {"word": "EUR", "x": 11, "y": 8, "dir": "h"},
      {"word": "BID", "x": 9, "y": 11, "dir": "h"},
      {"word": "DIE", "x": 12, "y": 4, "dir": "h"},
      {"word": "DEL", "x": 14, "y": 3, "dir": "v"},
      {"word": "LIB", "x": 5, "y": 3, "dir": "h"},
      {"word": "DER", "x": 14, "y": 3, "dir": "h"},
      {"word": "LIE", "x": 14, "y": 5, "dir": "h"},
      {"word": "DIR", "x": 16, "y": 1, "dir": "v"},
      {"word": "IDE", "x": 15, "y": 5, "dir": "v"},
      {"word": "RID", "x": 13, "y": 8, "dir": "v"},
      {"word": "URI", "x": 1, "y": 7, "dir": "h"},
      {"word": "DUI", "x": 6, "y": 1, "dir": "v"},
      {"word": "LID", "x": 14, "y": 1, "dir": "h"},
      {"word": "LEU", "x": 14, "y": 7, "dir": "h"},
    ],
  ),
  // LEVEL 39
  GameLevel(
    letters: ["I", "I", "O", "R", "S", "S", "T", "V"],
    rows: 15,
    cols: 15,
    grid: [
      {"word": "VISITORS", "x": 5, "y": 5, "dir": "h"},
      {"word": "VISITOR", "x": 5, "y": 5, "dir": "v"},
      {"word": "VISITS", "x": 7, "y": 3, "dir": "v"},
      {"word": "VISIT", "x": 9, "y": 1, "dir": "v"},
      {"word": "SORTS", "x": 11, "y": 3, "dir": "v"},
      {"word": "SORT", "x": 2, "y": 9, "dir": "h"},
      {"word": "ROSS", "x": 2, "y": 7, "dir": "h"},
      {"word": "TRIO", "x": 4, "y": 11, "dir": "h"},
      {"word": "ITS", "x": 5, "y": 8, "dir": "h"},
      {"word": "RSS", "x": 10, "y": 7, "dir": "h"},
      {"word": "ISO", "x": 3, "y": 5, "dir": "v"},
      {"word": "SIR", "x": 8, "y": 2, "dir": "h"},
      {"word": "SIT", "x": 11, "y": 3, "dir": "h"},
      {"word": "SRI", "x": 2, "y": 9, "dir": "v"},
      {"word": "TVS", "x": 4, "y": 11, "dir": "v"},
      {"word": "RIO", "x": 10, "y": 7, "dir": "v"},
      {"word": "TRI", "x": 1, "y": 5, "dir": "h"},
      {"word": "IST", "x": 6, "y": 11, "dir": "v"},
      {"word": "VII", "x": 12, "y": 1, "dir": "v"},
      {"word": "STR", "x": 12, "y": 7, "dir": "v"},
      {"word": "IRS", "x": 2, "y": 13, "dir": "h"},
    ],
  ),
  // LEVEL 40
  GameLevel(
    letters: ["A", "G", "G", "H", "I", "N", "N"],
    rows: 10,
    cols: 10,
    grid: [
      {"word": "HANGING", "x": 2, "y": 4, "dir": "h"},
      {"word": "AGING", "x": 3, "y": 4, "dir": "v"},
      {"word": "GAIN", "x": 4, "y": 1, "dir": "v"},
      {"word": "GANG", "x": 5, "y": 4, "dir": "v"},
      {"word": "HANG", "x": 7, "y": 2, "dir": "v"},
      {"word": "INN", "x": 3, "y": 6, "dir": "h"},
      {"word": "ANN", "x": 1, "y": 7, "dir": "h"},
      {"word": "ING", "x": 2, "y": 1, "dir": "h"},
      {"word": "IAN", "x": 1, "y": 6, "dir": "v"},
      {"word": "GIG", "x": 5, "y": 7, "dir": "h"},
    ],
  ),
  // LEVEL 41
  GameLevel(
    letters: ["E", "I", "M", "O", "P", "R", "S"],
    rows: 20,
    cols: 21,
    grid: [
      {"word": "PROMISE", "x": 11, "y": 8, "dir": "h"},
      {"word": "IMPOSE", "x": 11, "y": 6, "dir": "v"},
      {"word": "PRIME", "x": 14, "y": 5, "dir": "v"},
      {"word": "POEMS", "x": 16, "y": 4, "dir": "v"},
      {"word": "SPERM", "x": 7, "y": 7, "dir": "h"},
      {"word": "MORE", "x": 8, "y": 11, "dir": "h"},
      {"word": "SOME", "x": 7, "y": 7, "dir": "v"},
      {"word": "ROSE", "x": 9, "y": 4, "dir": "v"},
      {"word": "RISE", "x": 10, "y": 11, "dir": "v"},
      {"word": "ROME", "x": 5, "y": 9, "dir": "h"},
      {"word": "SEMI", "x": 10, "y": 13, "dir": "h"},
      {"word": "RIPE", "x": 9, "y": 4, "dir": "h"},
      {"word": "POEM", "x": 16, "y": 4, "dir": "h"},
      {"word": "PROS", "x": 5, "y": 8, "dir": "v"},
      {"word": "ROPE", "x": 7, "y": 14, "dir": "h"},
      {"word": "MSIE", "x": 12, "y": 13, "dir": "v"},
      {"word": "POSE", "x": 12, "y": 1, "dir": "v"},
      {"word": "PER", "x": 18, "y": 3, "dir": "v"},
      {"word": "SEP", "x": 11, "y": 10, "dir": "h"},
      {"word": "PRO", "x": 14, "y": 5, "dir": "h"},
      {"word": "PRE", "x": 7, "y": 13, "dir": "v"},
      {"word": "ROM", "x": 11, "y": 2, "dir": "h"},
      {"word": "ISO", "x": 7, "y": 5, "dir": "h"},
      {"word": "SIR", "x": 11, "y": 15, "dir": "h"},
      {"word": "RES", "x": 3, "y": 11, "dir": "h"},
      {"word": "REP", "x": 3, "y": 8, "dir": "h"},
      {"word": "SRI", "x": 7, "y": 3, "dir": "v"},
      {"word": "RPM", "x": 3, "y": 11, "dir": "v"},
      {"word": "MRS", "x": 3, "y": 7, "dir": "v"},
      {"word": "ISP", "x": 5, "y": 13, "dir": "h"},
      {"word": "OEM", "x": 1, "y": 13, "dir": "h"},
      {"word": "PIE", "x": 9, "y": 14, "dir": "v"},
      {"word": "POS", "x": 5, "y": 3, "dir": "h"},
      {"word": "POR", "x": 1, "y": 12, "dir": "v"},
      {"word": "SIM", "x": 1, "y": 7, "dir": "h"},
      {"word": "RIP", "x": 5, "y": 1, "dir": "v"},
      {"word": "RIM", "x": 5, "y": 1, "dir": "h"},
      {"word": "SER", "x": 8, "y": 16, "dir": "h"},
      {"word": "SIE", "x": 5, "y": 15, "dir": "h"},
      {"word": "ERP", "x": 17, "y": 8, "dir": "v"},
      {"word": "IRS", "x": 1, "y": 9, "dir": "h"},
      {"word": "EOS", "x": 1, "y": 5, "dir": "v"},
      {"word": "PSI", "x": 3, "y": 2, "dir": "h"},
      {"word": "SIP", "x": 8, "y": 16, "dir": "v"},
      {"word": "IPS", "x": 5, "y": 13, "dir": "v"},
    ],
  ),
  // LEVEL 42
  GameLevel(
    letters: ["E", "G", "I", "I", "N", "V", "W"],
    rows: 10,
    cols: 14,
    grid: [
      {"word": "VIEWING", "x": 5, "y": 5, "dir": "h"},
      {"word": "GIVEN", "x": 5, "y": 3, "dir": "v"},
      {"word": "VIEW", "x": 7, "y": 3, "dir": "v"},
      {"word": "GIVE", "x": 9, "y": 4, "dir": "v"},
      {"word": "WINE", "x": 2, "y": 6, "dir": "h"},
      {"word": "WING", "x": 11, "y": 2, "dir": "v"},
      {"word": "NEW", "x": 8, "y": 7, "dir": "h"},
      {"word": "WIN", "x": 2, "y": 6, "dir": "v"},
      {"word": "ING", "x": 3, "y": 3, "dir": "h"},
      {"word": "ENG", "x": 1, "y": 8, "dir": "h"},
      {"word": "GEN", "x": 4, "y": 1, "dir": "v"},
      {"word": "VII", "x": 10, "y": 3, "dir": "h"},
    ],
  ),
  // LEVEL 43
  GameLevel(
    letters: ["A", "E", "E", "R", "R", "S", "T", "U"],
    rows: 22,
    cols: 21,
    grid: [
      {"word": "TREASURE", "x": 7, "y": 10, "dir": "h"},
      {"word": "REUTERS", "x": 7, "y": 7, "dir": "v"},
      {"word": "EASTER", "x": 9, "y": 10, "dir": "v"},
      {"word": "ARREST", "x": 11, "y": 6, "dir": "v"},
      {"word": "RATES", "x": 13, "y": 10, "dir": "v"},
      {"word": "TREES", "x": 5, "y": 8, "dir": "h"},
      {"word": "RESET", "x": 5, "y": 13, "dir": "h"},
      {"word": "TEARS", "x": 6, "y": 15, "dir": "h"},
      {"word": "USER", "x": 11, "y": 13, "dir": "h"},
      {"word": "RATE", "x": 14, "y": 7, "dir": "v"},
      {"word": "EAST", "x": 10, "y": 6, "dir": "h"},
      {"word": "STAR", "x": 5, "y": 7, "dir": "v"},
      {"word": "SURE", "x": 10, "y": 15, "dir": "v"},
      {"word": "ARTS", "x": 8, "y": 15, "dir": "v"},
      {"word": "TRUE", "x": 6, "y": 15, "dir": "v"},
      {"word": "TREE", "x": 14, "y": 9, "dir": "h"},
      {"word": "REST", "x": 14, "y": 7, "dir": "h"},
      {"word": "RARE", "x": 10, "y": 3, "dir": "v"},
      {"word": "SEAT", "x": 13, "y": 3, "dir": "v"},
      {"word": "REAR", "x": 2, "y": 10, "dir": "h"},
      {"word": "EASE", "x": 10, "y": 18, "dir": "h"},
      {"word": "RATS", "x": 2, "y": 7, "dir": "h"},
      {"word": "EARS", "x": 16, "y": 9, "dir": "v"},
      {"word": "TEAR", "x": 3, "y": 16, "dir": "h"},
      {"word": "ARE", "x": 5, "y": 12, "dir": "v"},
      {"word": "USE", "x": 10, "y": 16, "dir": "h"},
      {"word": "SEE", "x": 4, "y": 18, "dir": "h"},
      {"word": "SET", "x": 17, "y": 5, "dir": "v"},
      {"word": "ART", "x": 9, "y": 3, "dir": "h"},
      {"word": "USA", "x": 3, "y": 5, "dir": "v"},
      {"word": "EUR", "x": 8, "y": 5, "dir": "h"},
      {"word": "USR", "x": 15, "y": 12, "dir": "h"},
      {"word": "SAT", "x": 13, "y": 3, "dir": "h"},
      {"word": "TUE", "x": 15, "y": 5, "dir": "v"},
      {"word": "SEA", "x": 3, "y": 9, "dir": "v"},
      {"word": "EST", "x": 13, "y": 18, "dir": "v"},
      {"word": "EAT", "x": 3, "y": 14, "dir": "v"},
      {"word": "TEA", "x": 9, "y": 1, "dir": "v"},
      {"word": "RES", "x": 8, "y": 4, "dir": "v"},
      {"word": "ERA", "x": 5, "y": 18, "dir": "v"},
      {"word": "EAR", "x": 17, "y": 6, "dir": "h"},
      {"word": "SUR", "x": 2, "y": 5, "dir": "h"},
      {"word": "TEE", "x": 13, "y": 20, "dir": "h"},
      {"word": "SUE", "x": 1, "y": 14, "dir": "h"},
      {"word": "RAT", "x": 11, "y": 1, "dir": "v"},
      {"word": "STE", "x": 7, "y": 2, "dir": "h"},
      {"word": "SER", "x": 6, "y": 4, "dir": "h"},
      {"word": "AUS", "x": 11, "y": 18, "dir": "v"},
      {"word": "STR", "x": 19, "y": 4, "dir": "v"},
      {"word": "TAR", "x": 8, "y": 17, "dir": "h"},
      {"word": "EAU", "x": 4, "y": 20, "dir": "h"},
      {"word": "ATE", "x": 15, "y": 18, "dir": "v"},
    ],
  ),
  // LEVEL 44
  GameLevel(
    letters: ["A", "C", "E", "E", "G", "H", "N", "X"],
    rows: 13,
    cols: 15,
    grid: [
      {"word": "EXCHANGE", "x": 4, "y": 8, "dir": "h"},
      {"word": "CHANGE", "x": 4, "y": 3, "dir": "v"},
      {"word": "HENCE", "x": 6, "y": 5, "dir": "v"},
      {"word": "EACH", "x": 8, "y": 7, "dir": "v"},
      {"word": "GENE", "x": 10, "y": 8, "dir": "v"},
      {"word": "HANG", "x": 1, "y": 7, "dir": "h"},
      {"word": "CHEN", "x": 4, "y": 3, "dir": "h"},
      {"word": "CHAN", "x": 7, "y": 10, "dir": "h"},
      {"word": "CAGE", "x": 11, "y": 5, "dir": "v"},
      {"word": "ACNE", "x": 2, "y": 7, "dir": "v"},
      {"word": "EXEC", "x": 10, "y": 11, "dir": "h"},
      {"word": "CAN", "x": 7, "y": 1, "dir": "v"},
      {"word": "AGE", "x": 11, "y": 6, "dir": "h"},
      {"word": "NEC", "x": 9, "y": 5, "dir": "h"},
      {"word": "ENG", "x": 1, "y": 9, "dir": "h"},
      {"word": "ACE", "x": 12, "y": 9, "dir": "v"},
      {"word": "GEN", "x": 13, "y": 5, "dir": "v"},
    ],
  ),
  // LEVEL 45
  GameLevel(
    letters: ["A", "B", "E", "M", "S", "S", "Y"],
    rows: 15,
    cols: 25,
    grid: [
      {"word": "EMBASSY", "x": 11, "y": 7, "dir": "h"},
      {"word": "MAYBE", "x": 11, "y": 3, "dir": "v"},
      {"word": "ESSAY", "x": 14, "y": 4, "dir": "v"},
      {"word": "BASES", "x": 16, "y": 5, "dir": "v"},
      {"word": "EBAY", "x": 9, "y": 4, "dir": "h"},
      {"word": "SAME", "x": 16, "y": 9, "dir": "h"},
      {"word": "EASY", "x": 9, "y": 4, "dir": "v"},
      {"word": "SAYS", "x": 6, "y": 6, "dir": "h"},
      {"word": "BASE", "x": 16, "y": 5, "dir": "h"},
      {"word": "MASS", "x": 12, "y": 7, "dir": "v"},
      {"word": "BASS", "x": 6, "y": 4, "dir": "v"},
      {"word": "BEAM", "x": 19, "y": 8, "dir": "v"},
      {"word": "MESS", "x": 18, "y": 3, "dir": "v"},
      {"word": "MESA", "x": 10, "y": 9, "dir": "h"},
      {"word": "SEAS", "x": 3, "y": 7, "dir": "h"},
      {"word": "MAY", "x": 19, "y": 11, "dir": "h"},
      {"word": "YES", "x": 3, "y": 5, "dir": "v"},
      {"word": "SAY", "x": 21, "y": 9, "dir": "v"},
      {"word": "BAY", "x": 1, "y": 5, "dir": "h"},
      {"word": "SEA", "x": 21, "y": 9, "dir": "h"},
      {"word": "SAM", "x": 16, "y": 3, "dir": "h"},
      {"word": "SMS", "x": 10, "y": 8, "dir": "v"},
      {"word": "AMY", "x": 17, "y": 9, "dir": "v"},
      {"word": "SYS", "x": 16, "y": 1, "dir": "v"},
      {"word": "MBA", "x": 5, "y": 4, "dir": "h"},
      {"word": "ABS", "x": 5, "y": 7, "dir": "v"},
      {"word": "AYE", "x": 20, "y": 11, "dir": "v"},
      {"word": "YEA", "x": 2, "y": 3, "dir": "v"},
      {"word": "MAS", "x": 23, "y": 8, "dir": "v"},
      {"word": "BYE", "x": 1, "y": 5, "dir": "v"},
      {"word": "SAS", "x": 8, "y": 10, "dir": "h"},
      {"word": "MAE", "x": 18, "y": 13, "dir": "h"},
    ],
  ),
  // LEVEL 46
  GameLevel(
    letters: ["D", "E", "E", "J", "N", "O", "Y"],
    rows: 17,
    cols: 13,
    grid: [
      {"word": "ENJOYED", "x": 3, "y": 8, "dir": "h"},
      {"word": "ENJOY", "x": 3, "y": 8, "dir": "v"},
      {"word": "NEED", "x": 8, "y": 7, "dir": "v"},
      {"word": "DONE", "x": 6, "y": 7, "dir": "v"},
      {"word": "NODE", "x": 2, "y": 11, "dir": "h"},
      {"word": "EYED", "x": 5, "y": 11, "dir": "v"},
      {"word": "DENY", "x": 8, "y": 10, "dir": "h"},
      {"word": "EDEN", "x": 4, "y": 5, "dir": "v"},
      {"word": "ONE", "x": 10, "y": 9, "dir": "v"},
      {"word": "END", "x": 5, "y": 13, "dir": "h"},
      {"word": "EYE", "x": 4, "y": 5, "dir": "h"},
      {"word": "JOE", "x": 6, "y": 3, "dir": "v"},
      {"word": "DON", "x": 1, "y": 9, "dir": "h"},
      {"word": "JOY", "x": 6, "y": 3, "dir": "h"},
      {"word": "DEN", "x": 7, "y": 13, "dir": "v"},
      {"word": "NEO", "x": 7, "y": 1, "dir": "v"},
      {"word": "YEN", "x": 8, "y": 3, "dir": "v"},
    ],
  ),
  // LEVEL 47
  GameLevel(
    letters: ["A", "E", "I", "L", "M", "N", "R", "T"],
    rows: 27,
    cols: 27,
    grid: [
      {"word": "TERMINAL", "x": 11, "y": 11, "dir": "h"},
      {"word": "MINERAL", "x": 12, "y": 8, "dir": "v"},
      {"word": "RENTAL", "x": 16, "y": 9, "dir": "v"},
      {"word": "RETAIL", "x": 18, "y": 6, "dir": "v"},
      {"word": "MARTIN", "x": 14, "y": 11, "dir": "v"},
      {"word": "MARINE", "x": 9, "y": 9, "dir": "h"},
      {"word": "MENTAL", "x": 7, "y": 14, "dir": "h"},
      {"word": "REMAIN", "x": 18, "y": 6, "dir": "h"},
      {"word": "LINEAR", "x": 16, "y": 14, "dir": "h"},
      {"word": "RETAIN", "x": 9, "y": 16, "dir": "h"},
      {"word": "EMAIL", "x": 9, "y": 8, "dir": "v"},
      {"word": "LEARN", "x": 21, "y": 4, "dir": "v"},
      {"word": "LATER", "x": 20, "y": 13, "dir": "v"},
      {"word": "TRIAL", "x": 11, "y": 16, "dir": "v"},
      {"word": "METAL", "x": 7, "y": 14, "dir": "v"},
      {"word": "LATIN", "x": 23, "y": 2, "dir": "v"},
      {"word": "ALERT", "x": 18, "y": 16, "dir": "h"},
      {"word": "TRAIN", "x": 9, "y": 19, "dir": "h"},
      {"word": "ANIME", "x": 14, "y": 7, "dir": "h"},
      {"word": "INTEL", "x": 18, "y": 10, "dir": "h"},
      {"word": "MAINE", "x": 19, "y": 2, "dir": "v"},
      {"word": "TRAIL", "x": 5, "y": 12, "dir": "h"},
      {"word": "MEANT", "x": 3, "y": 16, "dir": "h"},
      {"word": "INTER", "x": 20, "y": 8, "dir": "h"},
      {"word": "MARIE", "x": 5, "y": 8, "dir": "h"},
      {"word": "ALIEN", "x": 18, "y": 16, "dir": "v"},
      {"word": "ALTER", "x": 5, "y": 10, "dir": "v"},
      {"word": "TIMER", "x": 22, "y": 16, "dir": "v"},
      {"word": "MILAN", "x": 21, "y": 2, "dir": "h"},
      {"word": "MERIT", "x": 3, "y": 16, "dir": "v"},
      {"word": "REALM", "x": 15, "y": 2, "dir": "h"},
      {"word": "TAMIL", "x": 9, "y": 19, "dir": "v"},
      {"word": "TIME", "x": 15, "y": 19, "dir": "h"},
      {"word": "NAME", "x": 14, "y": 6, "dir": "v"},
      {"word": "MAIL", "x": 15, "y": 17, "dir": "h"},
      {"word": "REAL", "x": 24, "y": 8, "dir": "v"},
      {"word": "ITEM", "x": 5, "y": 5, "dir": "v"},
      {"word": "LINE", "x": 22, "y": 10, "dir": "v"},
      {"word": "RATE", "x": 4, "y": 10, "dir": "h"},
      {"word": "MAIN", "x": 22, "y": 18, "dir": "h"},
      {"word": "TEAM", "x": 3, "y": 20, "dir": "h"},
      {"word": "TERM", "x": 20, "y": 20, "dir": "h"},
      {"word": "NEAR", "x": 13, "y": 19, "dir": "v"},
      {"word": "MEAN", "x": 16, "y": 1, "dir": "v"},
      {"word": "MALE", "x": 5, "y": 18, "dir": "h"},
      {"word": "LATE", "x": 21, "y": 4, "dir": "h"},
      {"word": "ANTI", "x": 8, "y": 5, "dir": "v"},
      {"word": "RENT", "x": 2, "y": 6, "dir": "h"},
      {"word": "MINE", "x": 2, "y": 13, "dir": "h"},
      {"word": "RAIN", "x": 7, "y": 22, "dir": "h"},
      {"word": "LANE", "x": 25, "y": 16, "dir": "v"},
      {"word": "IRAN", "x": 16, "y": 19, "dir": "v"},
      {"word": "MILE", "x": 23, "y": 20, "dir": "v"},
      {"word": "EARN", "x": 11, "y": 6, "dir": "h"},
      {"word": "MEAT", "x": 5, "y": 18, "dir": "v"},
      {"word": "RAIL", "x": 7, "y": 5, "dir": "h"},
      {"word": "MEAL", "x": 3, "y": 5, "dir": "v"},
      {"word": "META", "x": 22, "y": 23, "dir": "h"},
      {"word": "MINT", "x": 14, "y": 4, "dir": "h"},
      {"word": "NEIL", "x": 3, "y": 11, "dir": "v"},
      {"word": "TAIL", "x": 20, "y": 20, "dir": "v"},
      {"word": "TRIM", "x": 7, "y": 21, "dir": "v"},
      {"word": "MART", "x": 25, "y": 22, "dir": "v"},
      {"word": "NAIL", "x": 10, "y": 2, "dir": "v"},
      {"word": "MENT", "x": 22, "y": 25, "dir": "h"},
      {"word": "TIER", "x": 7, "y": 2, "dir": "v"},
      {"word": "EARL", "x": 22, "y": 13, "dir": "h"},
      {"word": "MALI", "x": 4, "y": 23, "dir": "h"},
      {"word": "MRNA", "x": 12, "y": 3, "dir": "v"},
      {"word": "INTL", "x": 20, "y": 8, "dir": "v"},
      {"word": "ARE", "x": 1, "y": 17, "dir": "h"},
      {"word": "ART", "x": 6, "y": 8, "dir": "v"},
      {"word": "MAN", "x": 12, "y": 21, "dir": "h"},
      {"word": "MEN", "x": 1, "y": 11, "dir": "h"},
      {"word": "AIR", "x": 12, "y": 13, "dir": "h"},
      {"word": "LET", "x": 5, "y": 2, "dir": "h"},
      {"word": "NET", "x": 16, "y": 22, "dir": "h"},
      {"word": "MAR", "x": 4, "y": 23, "dir": "v"},
      {"word": "TEL", "x": 1, "y": 8, "dir": "h"},
      {"word": "INT", "x": 25, "y": 1, "dir": "v"},
      {"word": "TEN", "x": 18, "y": 22, "dir": "v"},
      {"word": "MET", "x": 15, "y": 17, "dir": "v"},
      {"word": "EAT", "x": 1, "y": 16, "dir": "v"},
      {"word": "AIM", "x": 10, "y": 3, "dir": "h"},
      {"word": "TEA", "x": 2, "y": 24, "dir": "h"},
      {"word": "RAM", "x": 24, "y": 13, "dir": "v"},
      {"word": "ERA", "x": 7, "y": 10, "dir": "v"},
      {"word": "RAN", "x": 4, "y": 25, "dir": "h"},
      {"word": "TIE", "x": 10, "y": 14, "dir": "v"},
      {"word": "IAN", "x": 16, "y": 24, "dir": "h"},
      {"word": "MIT", "x": 2, "y": 22, "dir": "v"},
      {"word": "ALT", "x": 5, "y": 1, "dir": "v"},
      {"word": "ATM", "x": 1, "y": 7, "dir": "v"},
      {"word": "RNA", "x": 16, "y": 9, "dir": "h"},
      {"word": "NAT", "x": 3, "y": 3, "dir": "h"},
      {"word": "LEN", "x": 3, "y": 1, "dir": "v"},
      {"word": "MIL", "x": 1, "y": 1, "dir": "h"},
      {"word": "MAI", "x": 1, "y": 1, "dir": "v"},
    ],
  ),
  // LEVEL 48
  GameLevel(
    letters: ["A", "A", "D", "E", "L", "R", "Y"],
    rows: 17,
    cols: 22,
    grid: [
      {"word": "ALREADY", "x": 6, "y": 7, "dir": "h"},
      {"word": "EARLY", "x": 6, "y": 6, "dir": "v"},
      {"word": "READY", "x": 8, "y": 7, "dir": "v"},
      {"word": "LAYER", "x": 10, "y": 6, "dir": "v"},
      {"word": "DELAY", "x": 12, "y": 3, "dir": "v"},
      {"word": "RELAY", "x": 2, "y": 10, "dir": "h"},
      {"word": "YEAR", "x": 3, "y": 8, "dir": "h"},
      {"word": "READ", "x": 10, "y": 10, "dir": "h"},
      {"word": "REAL", "x": 11, "y": 4, "dir": "h"},
      {"word": "AREA", "x": 12, "y": 6, "dir": "h"},
      {"word": "LEAD", "x": 4, "y": 10, "dir": "v"},
      {"word": "DEAL", "x": 13, "y": 10, "dir": "v"},
      {"word": "LADY", "x": 3, "y": 5, "dir": "v"},
      {"word": "DEAR", "x": 2, "y": 12, "dir": "h"},
      {"word": "YARD", "x": 15, "y": 5, "dir": "v"},
      {"word": "DALE", "x": 12, "y": 12, "dir": "h"},
      {"word": "RELY", "x": 1, "y": 5, "dir": "h"},
      {"word": "EARL", "x": 14, "y": 1, "dir": "v"},
      {"word": "DARE", "x": 2, "y": 12, "dir": "v"},
      {"word": "YALE", "x": 15, "y": 5, "dir": "h"},
      {"word": "ARE", "x": 8, "y": 9, "dir": "h"},
      {"word": "DAY", "x": 15, "y": 8, "dir": "h"},
      {"word": "RED", "x": 1, "y": 7, "dir": "h"},
      {"word": "LED", "x": 15, "y": 11, "dir": "v"},
      {"word": "DEL", "x": 13, "y": 1, "dir": "h"},
      {"word": "RAY", "x": 4, "y": 3, "dir": "v"},
      {"word": "DRY", "x": 1, "y": 14, "dir": "h"},
      {"word": "DER", "x": 1, "y": 3, "dir": "v"},
      {"word": "ERA", "x": 16, "y": 3, "dir": "v"},
      {"word": "LAY", "x": 15, "y": 11, "dir": "h"},
      {"word": "EAR", "x": 18, "y": 5, "dir": "v"},
      {"word": "AYE", "x": 7, "y": 11, "dir": "h"},
      {"word": "ADA", "x": 4, "y": 4, "dir": "h"},
      {"word": "YEA", "x": 17, "y": 11, "dir": "v"},
      {"word": "ALA", "x": 18, "y": 6, "dir": "h"},
    ],
  ),
  // LEVEL 49
  GameLevel(
    letters: ["A", "C", "E", "I", "N", "O", "R", "S"],
    rows: 26,
    cols: 27,
    grid: [
      {"word": "SCENARIO", "x": 11, "y": 11, "dir": "h"},
      {"word": "CASINO", "x": 11, "y": 9, "dir": "v"},
      {"word": "REASON", "x": 13, "y": 10, "dir": "v"},
      {"word": "SENIOR", "x": 16, "y": 6, "dir": "v"},
      {"word": "SINCE", "x": 8, "y": 9, "dir": "h"},
      {"word": "SCORE", "x": 18, "y": 9, "dir": "v"},
      {"word": "OCEAN", "x": 7, "y": 13, "dir": "h"},
      {"word": "NOISE", "x": 13, "y": 15, "dir": "h"},
      {"word": "RAISE", "x": 13, "y": 6, "dir": "h"},
      {"word": "COINS", "x": 13, "y": 8, "dir": "h"},
      {"word": "ACRES", "x": 8, "y": 5, "dir": "v"},
      {"word": "ICONS", "x": 7, "y": 11, "dir": "v"},
      {"word": "RACES", "x": 18, "y": 12, "dir": "h"},
      {"word": "ARISE", "x": 15, "y": 13, "dir": "v"},
      {"word": "OSCAR", "x": 13, "y": 2, "dir": "v"},
      {"word": "SONIC", "x": 18, "y": 9, "dir": "h"},
      {"word": "CASIO", "x": 7, "y": 5, "dir": "h"},
      {"word": "CASE", "x": 17, "y": 3, "dir": "v"},
      {"word": "CARE", "x": 6, "y": 7, "dir": "h"},
      {"word": "ONCE", "x": 12, "y": 17, "dir": "h"},
      {"word": "CARS", "x": 4, "y": 15, "dir": "h"},
      {"word": "NEAR", "x": 9, "y": 12, "dir": "v"},
      {"word": "NICE", "x": 22, "y": 7, "dir": "v"},
      {"word": "RACE", "x": 15, "y": 3, "dir": "h"},
      {"word": "CORE", "x": 20, "y": 12, "dir": "v"},
      {"word": "ROSE", "x": 11, "y": 4, "dir": "v"},
      {"word": "ONES", "x": 9, "y": 2, "dir": "v"},
      {"word": "ICON", "x": 11, "y": 2, "dir": "h"},
      {"word": "IRON", "x": 20, "y": 6, "dir": "v"},
      {"word": "RISE", "x": 6, "y": 15, "dir": "v"},
      {"word": "ERIC", "x": 17, "y": 15, "dir": "v"},
      {"word": "RAIN", "x": 5, "y": 11, "dir": "h"},
      {"word": "IRAN", "x": 19, "y": 7, "dir": "h"},
      {"word": "RICE", "x": 11, "y": 4, "dir": "h"},
      {"word": "EARN", "x": 22, "y": 10, "dir": "h"},
      {"word": "SCAN", "x": 13, "y": 13, "dir": "h"},
      {"word": "SEAN", "x": 22, "y": 12, "dir": "v"},
      {"word": "RICO", "x": 4, "y": 13, "dir": "v"},
      {"word": "RICA", "x": 24, "y": 10, "dir": "v"},
      {"word": "CORN", "x": 12, "y": 16, "dir": "v"},
      {"word": "NOSE", "x": 3, "y": 18, "dir": "h"},
      {"word": "COIN", "x": 14, "y": 17, "dir": "v"},
      {"word": "ASIN", "x": 6, "y": 3, "dir": "h"},
      {"word": "CIAO", "x": 17, "y": 18, "dir": "h"},
      {"word": "ACER", "x": 6, "y": 6, "dir": "v"},
      {"word": "RENO", "x": 1, "y": 16, "dir": "h"},
      {"word": "EARS", "x": 2, "y": 13, "dir": "h"},
      {"word": "CONS", "x": 20, "y": 17, "dir": "v"},
      {"word": "ACRE", "x": 3, "y": 8, "dir": "h"},
      {"word": "ACNE", "x": 2, "y": 10, "dir": "v"},
      {"word": "ROSA", "x": 3, "y": 6, "dir": "h"},
      {"word": "ARE", "x": 18, "y": 1, "dir": "v"},
      {"word": "CAN", "x": 25, "y": 8, "dir": "v"},
      {"word": "ONE", "x": 4, "y": 18, "dir": "v"},
      {"word": "CAR", "x": 10, "y": 18, "dir": "h"},
      {"word": "AIR", "x": 1, "y": 14, "dir": "v"},
      {"word": "SAN", "x": 17, "y": 5, "dir": "h"},
      {"word": "INC", "x": 10, "y": 16, "dir": "h"},
      {"word": "SEA", "x": 16, "y": 1, "dir": "v"},
      {"word": "SON", "x": 6, "y": 17, "dir": "h"},
      {"word": "ICE", "x": 14, "y": 19, "dir": "h"},
      {"word": "SEC", "x": 7, "y": 3, "dir": "v"},
      {"word": "NOR", "x": 22, "y": 15, "dir": "h"},
      {"word": "CON", "x": 20, "y": 17, "dir": "h"},
      {"word": "SRC", "x": 20, "y": 20, "dir": "h"},
      {"word": "ISO", "x": 18, "y": 18, "dir": "v"},
      {"word": "SIR", "x": 3, "y": 4, "dir": "v"},
      {"word": "RES", "x": 17, "y": 16, "dir": "h"},
      {"word": "SCI", "x": 1, "y": 11, "dir": "h"},
      {"word": "SIN", "x": 3, "y": 4, "dir": "h"},
      {"word": "ERA", "x": 22, "y": 13, "dir": "h"},
      {"word": "RAN", "x": 18, "y": 2, "dir": "h"},
      {"word": "RON", "x": 24, "y": 15, "dir": "v"},
      {"word": "EAR", "x": 4, "y": 20, "dir": "h"},
      {"word": "CEO", "x": 4, "y": 8, "dir": "v"},
      {"word": "SRI", "x": 1, "y": 5, "dir": "h"},
      {"word": "NEC", "x": 8, "y": 17, "dir": "v"},
      {"word": "RIO", "x": 21, "y": 20, "dir": "v"},
      {"word": "ARC", "x": 5, "y": 20, "dir": "v"},
      {"word": "ION", "x": 20, "y": 22, "dir": "h"},
      {"word": "ACE", "x": 7, "y": 19, "dir": "h"},
      {"word": "SEO", "x": 1, "y": 5, "dir": "v"},
      {"word": "INS", "x": 20, "y": 1, "dir": "v"},
      {"word": "REC", "x": 3, "y": 22, "dir": "h"},
      {"word": "IRC", "x": 10, "y": 16, "dir": "v"},
      {"word": "RNA", "x": 20, "y": 14, "dir": "h"},
      {"word": "ECO", "x": 16, "y": 19, "dir": "v"},
      {"word": "CIA", "x": 6, "y": 1, "dir": "v"},
      {"word": "NEO", "x": 22, "y": 22, "dir": "v"},
      {"word": "SER", "x": 20, "y": 3, "dir": "h"},
      {"word": "SOC", "x": 15, "y": 21, "dir": "h"},
      {"word": "SIE", "x": 15, "y": 21, "dir": "v"},
      {"word": "RCA", "x": 3, "y": 22, "dir": "v"},
      {"word": "COS", "x": 6, "y": 1, "dir": "h"},
      {"word": "IRS", "x": 20, "y": 22, "dir": "v"},
      {"word": "SAO", "x": 20, "y": 24, "dir": "h"},
      {"word": "ASN", "x": 3, "y": 24, "dir": "h"},
      {"word": "EOS", "x": 9, "y": 19, "dir": "v"},
      {"word": "CAS", "x": 17, "y": 21, "dir": "v"},
      {"word": "ISA", "x": 20, "y": 1, "dir": "h"},
      {"word": "SIC", "x": 1, "y": 23, "dir": "h"},
      {"word": "SEN", "x": 9, "y": 21, "dir": "h"},
      {"word": "SOA", "x": 16, "y": 1, "dir": "h"},
    ],
  ),
  // LEVEL 50
  GameLevel(
    letters: ["B", "G", "I", "N", "N", "R", "U"],
    rows: 15,
    cols: 14,
    grid: [
      {"word": "BURNING", "x": 3, "y": 8, "dir": "h"},
      {"word": "BRING", "x": 3, "y": 8, "dir": "v"},
      {"word": "RING", "x": 5, "y": 8, "dir": "v"},
      {"word": "BURN", "x": 6, "y": 5, "dir": "v"},
      {"word": "BIG", "x": 9, "y": 6, "dir": "v"},
      {"word": "RUN", "x": 1, "y": 11, "dir": "h"},
      {"word": "INN", "x": 7, "y": 8, "dir": "v"},
      {"word": "BIN", "x": 6, "y": 5, "dir": "h"},
      {"word": "BUG", "x": 9, "y": 6, "dir": "h"},
      {"word": "GNU", "x": 4, "y": 6, "dir": "v"},
      {"word": "GUN", "x": 8, "y": 3, "dir": "v"},
      {"word": "ING", "x": 11, "y": 4, "dir": "v"},
      {"word": "GUI", "x": 8, "y": 3, "dir": "h"},
      {"word": "RUG", "x": 1, "y": 11, "dir": "v"},
      {"word": "URI", "x": 10, "y": 1, "dir": "v"},
      {"word": "UNI", "x": 10, "y": 1, "dir": "h"},
    ],
  ),
];
